[package]
name = "mole"
version = "0.1.0"
authors = ["Joe Ling - uni laptop <josephling11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liquid = "0.20.1"
pulldown-cmark = "0.7.2"
serde_json = "1.0"
serde = "*"